[package]
name = "example_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plugin_interface = {path = "../plugin_interface"}
rand = "0.8.1"

[lib]
name = "my_plugin"
crate-type = ["dylib"] 